---

# Aptitude
- name: Install ZSH (Aptitude)
  apt:
    name: zsh
    state: present
  when: ansible_pkg_mgr == 'apt'

# Homebrew
- name: Install ZSH (Homebrew)
  homebrew:
    name: zsh
    state: present
  become: true
  become_user: "{{ zsh_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

# Yum
- name: Install ZSH (Yum)
  yum: pkg=zsh state=present
  when: ansible_pkg_mgr == 'yum'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Aptitude, Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'apt' and ansible_pkg_mgr != 'homebrew' and ansible_pkg_mgr != 'yum'

- name: Set zsh as the default shell (Linux)
  user: name={{ zsh_user }} shell={{ zsh_bin }}
  when: ansible_pkg_mgr != 'homebrew'

- name: Set zsh as the default shell (Homebrew)
  user: name={{ zsh_homebrew_user }} shell={{ zsh_homebrew_bin }}
  when: ansible_pkg_mgr == 'homebrew'
